BloggingSystem/BloggingSystem/Controllers/PostsController.cs
using BloggingSystemRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;

namespace BloggingSystem
{
	[Authorize]
	public class PostsController : BaseController
	{
		private readonly ILogger<PostsController> _logger;
		private readonly PostManager _postManager;

		public PostsController(ILogger<PostsController> logger, SubscribeManager subscribeManager, PostManager postManager)
			: base(subscribeManager)
		{
			_logger = logger;
			_postManager = postManager;
		}

		public async Task<IActionResult> IndexAsync(string author)
		{
			await FillSubscriptionsAsync();
			await FillNotificationsAsync();
			return View("Index", await _postManager.GetPostsAsync(author));
		}

		public async Task<IActionResult> CreateAsync()
		{
			await FillSubscriptionsAsync();
			await FillNotificationsAsync();
			return View("Create");
		}

		public async Task<IActionResult> PrivacyAsync()
		{
			await FillSubscriptionsAsync();
			await FillNotificationsAsync();
			return View("Privacy");
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error(string message)
		{
			return View(new ErrorViewModel 
			{ 
				RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
				Message = message
			});
		}

		[HttpPost]
		public async Task<IActionResult> CreateAsync(Post post, List<IFormFile> images)
		{
			try
			{
				var author = User.FindFirst(ClaimTypes.Name)?.Value;
				await _postManager.CreateAsync(author, post, images);
				_subscribeManager.Notify(author, $"{author} just posted \"{post.Title}\"");

				return Json(new
				{
					success = true
				});
			}
			catch (Exception ex)
			{
				var message = "Failed to create the post";
				_logger.LogError(ex, message);
				return Json(new
				{
					success = false,
					message
				});
			}
		}

		[HttpPost]
		public async Task<IActionResult> DeleteAsync(string postId)
		{
			try
			{
				await _postManager.DeleteAsync(postId);

				return Json(new
				{
					success = true
				});
			}
			catch (Exception ex)
			{
				var message = "Failed to delete the post";
				_logger.LogError(ex, message);
				return Json(new
				{
					success = false,
					message
				});
			}
		}

		[HttpPost]
		public async Task<IActionResult> AddCommentAsync(string postId, string commentContent)
		{
			try
			{
				var author = User.FindFirst(ClaimTypes.Name)?.Value;
				var newComment = await _postManager.AddCommentAsync(author, postId, commentContent);
				_subscribeManager.Notify(author, $"{author} just commented \"{commentContent}\"");

				if (newComment is null)
				{
					return NotFound("Post not found");
				}

				return Json(new
				{
					success = true,
					comment = new
					{
						id = newComment.Id.ToString(),
						author = newComment.Author,
						content = newComment.Content,
						createdAt = newComment.CreatedAt
					}
				});
			}
			catch (Exception ex)
			{
				var message = "Failed to add comment";
				_logger.LogError(ex, message);
				return Json(new
				{
					success = false,
					message
				});
			}
		}
	}
}

BloggingSystem/BloggingSystem/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BloggingSystem
{
	[Authorize]
	public class UsersController : BaseController
	{
		private readonly ILogger<UsersController> _logger;
		private readonly UserManager _userManager;

		public UsersController(ILogger<UsersController> logger, UserManager userManager, SubscribeManager subscribeManager)
			: base(subscribeManager)
		{
			_logger = logger;
			_userManager = userManager;
		}

		public async Task<IActionResult> AuthorDetailsAsync(string author)
		{
			if (author is null)
			{
				return NotFound();
			}

			var username = User.FindFirst(ClaimTypes.Name)?.Value;
			var subscriptions = await _subscribeManager.GetSubscriptionsAsync(username);

			ViewBag.Subscriptions = subscriptions;
			ViewBag.IsSubscribed = subscriptions.FirstOrDefault(sub => sub.Username.Equals(author)) is not null;
			await FillNotificationsAsync();

			return View("AuthorDetails", await _userManager.GetUserDetailsAsync(author));
		}

		public async Task<IActionResult> ProfileDetailsAsync(string author)
		{
			if (author is null)
			{
				return NotFound();
			}

			await FillSubscriptionsAsync();
			await FillNotificationsAsync();

			return View("ProfileDetails", await _userManager.GetUserDetailsAsync(author));
		}

		[HttpPost]
		public async Task<IActionResult> UpdateUserAsync(string firstName, string lastName, IFormFile photo)
		{
			try
			{
				var username = User.FindFirst(ClaimTypes.Name)?.Value;
				var photoUrl = await _userManager.UpdateUserDetailsAsync(username, firstName, lastName, photo);

				return Json(new
				{
					success = true,
					photo = photoUrl,
					firstName,
					lastName
				});
			}
			catch (Exception ex)
			{
				var message = "Failed to delete the post";
				_logger.LogError(ex, message);
				return Json(new
				{
					success = false,
					message
				});
			}
		}

		[HttpPost]
		public async Task<IActionResult> ToggleSubscriptionAsync(bool isSubscribed, string author)
		{
			try
			{
				var subscriber = User.FindFirst(ClaimTypes.Name)?.Value;

				if (isSubscribed)
				{
					await _subscribeManager.UnsubscribeAsync(author, subscriber);

					return Json(new
					{
						success = true
					});
				}

				return Json(new
				{
					success = true,
					subscription = await _subscribeManager.SubscribeAsync(author, subscriber)
				});
			}
			catch (Exception ex)
			{
				var message = $"Failed to {(isSubscribed ? "unsubscribe from" : "subscribe to")} {author}";
				_logger.LogError(ex, message);
				return Json(new
				{
					success = false,
					message
				});
			}
		}

		[HttpPost]
		public async Task<IActionResult> RemoveNotificationAsync(string subscriber, string notification)
		{
			try
			{
				await _subscribeManager.RemoveNotificationAsync(subscriber, notification);

				return Json(new
				{
					success = true
				});
			}
			catch (Exception ex)
			{
				var message = $"Failed to delete {notification} for {subscriber}";
				_logger.LogError(ex, message);
				return Json(new
				{
					success = false,
					message
				});
			}
		}
	}
}

BloggingSystem/BloggingSystem/Views/Shared/CommentsPartial.cshtml
@model BloggingSystemRepository.Post

<div class="card-footer">
	@if (Model.Comments != null && Model.Comments.Any())
	{
		<h5>Comments:</h5>
		<ul id="commentsContainer-@Model.Id">
			@foreach (var comment in Model.Comments)
			{
				<li>@comment.Content (@comment.Author on @comment.CreatedAt.ToString("MMMM dd, yyyy"))</li>
			}
		</ul>
	}
	<form class="commentForm" method="post" data-post-id="@Model.Id">
		<div class="input-group">
			<input type="text" id="commentContent-@Model.Id" name="commentContent" class="horizontal-input form-control" placeholder="Add a comment..." required />
			<div class="input-group-append">
				<button type="submit" class="btn btn-primary">
					<img src="/images/send-icon.png" alt="Send" style="width: 20px; height: 20px;" />
					Send
				</button>
			</div>
		</div>
	</form>
</div>

BloggingSystem/BloggingSystem/Views/Shared/NotificationsPartial.cshtml
@using System.Security.Claims
@model IEnumerable<string>

@{
	var username = User.FindFirstValue(ClaimTypes.Name);
}

<div class="dropdown">
	<i class="fa fa-bell" style="font-size:24px; margin-right: 15px;"></i>
	<div class="dropdown-content">
		<p class="dropdown-header">Notifications</p>
		@foreach (var notification in Model)
		{
			<a class="remove-notification" data-subscriber="@username" data-notification="@notification">@notification</a>
		}
	</div>
</div>

BloggingSystem/BloggingSystem/Views/Shared/PostContentPartial.cshtml
@model BloggingSystemRepository.Post

<div class="card-body">
	<p>@Model.Content</p>
	@if (Model.Images != null && Model.Images.All(image => image != null))
	{
		<div class="row">
			@foreach (var imageUrl in Model.Images)
			{
				<div class="col-md-3">
					<img src="@imageUrl" class="img-fluid" alt="Post Image" />
				</div>
			}
		</div>
	}
</div>

BloggingSystem/BloggingSystem/Views/Shared/SidebarPartial.cshtml
@model IEnumerable<BloggingSystemRepository.UserFollowInfo>

<div id="sidebar">
	<h4 class="text-center">Subscriptions</h4>
	<ul id="subscriptionContainer">
		@foreach (var subscription in Model)
		{
			<li id="subscription-@subscription.Username" class="d-flex align-items-center">
				<a asp-controller="Users" asp-action="AuthorDetails" asp-route-author="@subscription.Username">
					<img src="@(subscription.Photo is null ? "/images/profile-icon.png" : subscription.Photo)" class="subscription-icon" alt="subscription" />
					@subscription.Username
				</a>
			</li>
		}
	</ul>
</div>

BloggingSystem/BloggingSystem/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>@ViewData["Title"] - BloggingSystem</title>
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
		<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
		<link rel="stylesheet" href="~/BloggingSystem.styles.css" asp-append-version="true" />
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
	</head>
	<body>
		@if (User.Identity.IsAuthenticated)
		{
			<header>
				<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
					<div class="container-fluid">
						<a class="navbar-brand" asp-controller="Posts" asp-action="Index">BloggingSystem</a>
						<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
								aria-expanded="false" aria-label="Toggle navigation">
							<span class="navbar-toggler-icon"></span>
						</button>
						<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
							<ul class="navbar-nav flex-grow-1">
								<li class="nav-item">
									<a class="nav-link text-dark" asp-controller="Posts" asp-action="Index">Home</a>
								</li>
								<li class="nav-item">
									<a class="nav-link text-dark" asp-controller="Posts" asp-action="Privacy">Privacy</a>
								</li>
							</ul>
							<ul class="navbar-nav">
								<li class="nav-item">
									<div class="d-flex align-items-center profile-icon-container">
										@{
											var username = User.FindFirstValue(ClaimTypes.Name);
											var photoUrl = User.FindFirstValue(ClaimTypes.UserData);
										}
										@await Html.PartialAsync("NotificationsPartial", ViewBag.Notifications as IEnumerable<string>)
										<div class="dropdown">
											<div class="profile-icon">
												<img src="@photoUrl" alt="User profile" />
											</div>
											<div class="dropdown-content">
												<a asp-controller="Users" asp-action="ProfileDetails" asp-route-author="@username">My profile</a>
												<a class="nav-link text-dark" asp-controller="Auth" asp-action="Logout">Logout</a>
											</div>
										</div>
									</div>
								</li>
							</ul>
						</div>
					</div>
				</nav>
			</header>

			<span class="toggle-btn" onclick="toggleSidebar()">&#x22D8;</span>
			@await Html.PartialAsync("SidebarPartial", ViewBag.Subscriptions as IEnumerable<BloggingSystemRepository.UserFollowInfo>)
		}

		<div id="main-content" class="container">
			<main role="main" class="pb-3">
				@RenderBody()
			</main>
		</div>
	
		<footer class="border-top footer text-muted">
			<div class="container">
				&copy; 2024 - BloggingSystem - <a asp-controller="Posts" asp-action="Privacy">Privacy</a>
			</div>
		</footer>

		<script src="~/lib/jquery/dist/jquery.min.js"></script>
		<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
		<script src="~/js/site.js" asp-append-version="true"></script>
		@await RenderSectionAsync("Scripts", required: false)
	</body>
</html>